services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - minio

  api:
    build: .
    expose:
      - "3000"
    env_file:
      - .env
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    depends_on:
      - db
      - minio
    command: ./bin/rails server -b 0.0.0.0
    environment:
      RAILS_ENV: development

  db:
    image: postgres:16.1-alpine
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - "5432"

  minio:
    image: minio/minio:RELEASE.2025-02-07T23-21-09Z
    expose:
      - "9000"
      - "9001"
    env_file: ".env"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001" --address ":9000"
    environment:
      MINIO_BROWSER_REDIRECT_URL: http://localhost/minio
    restart: always

volumes:
  db_data: {}
  minio_data: {}
  bundle_cache: {}
