services:
  db:
    image: postgres:16.1-alpine
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:RELEASE.2025-02-07T23-21-09Z
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file: ".env"
    volumes:
      - ./data/minio:/data'
    command: server /data --console-address :9001
    restart: always

volumes:
  db_data: {}
  minio_data: {}
